import Head from 'next/head';
import Link from 'next/link';
import React, { useContext, useEffect } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Store } from '../utils/Store';
import { useState } from 'react';
import { signOut, useSession } from 'next-auth/react';
import { Menu } from '@headlessui/react';
import DropdownLink from './DropdownLink';
import Cookies from 'js-cookie';

export default function Layout({ title, children }) {
  const { status, data: session } = useSession();

  const { state, dispatch } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setcartItemsCount] = useState(0);
  useEffect(() => {
    setcartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  const logoutClickHandler = () => {
    Cookies.remove('cart');
    dispatch({ type: 'CART_RESET' });
    signOut({ callbackUrl: '/login' });
  };

  return (
    <>
      <Head>
        <title>{title ? title + ' - Amazona' : 'Amazona'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer position="bottom-center" limit={1} />

      <div className="flex min-h-screen flex-col justify-between">
        {/* header */}
        <header>
          <nav className="flex h-12 justify-between items-center shadow-md px-4">
            <Link href="/">
              <p className="text-xl font-bold">Amazona</p>
            </Link>
            <div className="flex">
              <Link className="p-3 flex space-x-3" href="/cart">
                <p>Cart</p>
                {cartItemsCount > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cartItemsCount}
                  </span>
                )}
              </Link>
              <div className=" flex items-center">
                {status === 'loading' ? (
                  'Loading'
                ) : session?.user ? (
                  <Menu as="div" className="relative inline-block">
                    <Menu.Button className="text-blue-400">
                      {session.user.name}
                    </Menu.Button>
                    <Menu.Items className="absolute right-1 w-56 origin-top-right bg-white shadow-lg">
                      <Menu.Item>
                        <DropdownLink
                          href="/profile"
                          className=" dropdown-link"
                        >
                          Profile
                        </DropdownLink>
                      </Menu.Item>
                      <Menu.Item>
                        <DropdownLink
                          href="/order-history"
                          className=" dropdown-link"
                        >
                          Order History
                        </DropdownLink>
                      </Menu.Item>
                      <Menu.Item>
                        <DropdownLink href="#" className=" dropdown-link">
                          <p onClick={logoutClickHandler}>Logout</p>
                        </DropdownLink>
                      </Menu.Item>
                    </Menu.Items>
                  </Menu>
                ) : (
                  <Link className="p-3" href="/login">
                    <p>Login</p>
                  </Link>
                )}
              </div>
            </div>
          </nav>
        </header>

        {/* main */}
        <main className="container m-auto mt-4 px-4">{children}</main>

        <footer className="h-12 flex justify-center items-center shadow-inner">
          <p>Copyright @ 2022 Amazona</p>
        </footer>
      </div>
    </>
  );
}
